In [1]:
import pandas as pd
import numpy as np

In [59]:
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

In [67]:
df = pd.read_csv('students.csv')
df = df.set_index('Name')  # 重设索引列
df

hw1   hw2 program
Name                         
Dorian     10.0  10.0    MSIS
Jeannine    6.0   7.0    MSIS
Iluminada   2.0   NaN     MBA
Luci        7.0   7.0    MSIS
Jenny       8.0   NaN     NaN
Demetria    2.0   4.0    MSIS
Michael     6.0  10.0     MBA
Garland     9.0   1.0    MSIS
Shelby      1.0  10.0    MSIS
Mercy       5.0   6.0    MSIS
John        NaN  10.0    MSIS

In [58]:
df.index
df.columns
df.values

array([[10.0, 10.0, 'MSIS'],
       [6.0, 7.0, 'MSIS'],
       [2.0, nan, 'MBA'],
       [7.0, 7.0, 'MSIS'],
       [8.0, nan, nan],
       [2.0, 4.0, 'MSIS'],
       [6.0, 10.0, 'MBA'],
       [9.0, 1.0, 'MSIS'],
       [1.0, 10.0, 'MSIS'],
       [5.0, 6.0, 'MSIS'],
       [nan, 10.0, 'MSIS']], dtype=object)

##### df.iloc[x,y]

In [80]:
df.iloc[3, 2]
df.iloc[2, :]

# 指定range
df.iloc[:4, -2:]  # 一至四行，倒数两列
df.iloc[[2, 4, 5], :]  # 选择第三、五、六行

'MSIS'

hw1          2
hw2        NaN
program    MBA
Name: Iluminada, dtype: object

hw2 program
Name                   
Dorian     10.0    MSIS
Jeannine    7.0    MSIS
Iluminada   NaN     MBA
Luci        7.0    MSIS

hw1  hw2 program
Name                       
Iluminada  2.0  NaN     MBA
Jenny      8.0  NaN     NaN
Demetria   2.0  4.0    MSIS

##### df.loc[x,y]

In [83]:
df.loc[:,'hw1']
df.hw1
df['hw1']
df.loc[:,['hw1','hw2']]

Name
Dorian       10.0
Jeannine      6.0
Iluminada     2.0
Luci          7.0
Jenny         8.0
Demetria      2.0
Michael       6.0
Garland       9.0
Shelby        1.0
Mercy         5.0
John          NaN
Name: hw1, dtype: float64

Name
Dorian       10.0
Jeannine      6.0
Iluminada     2.0
Luci          7.0
Jenny         8.0
Demetria      2.0
Michael       6.0
Garland       9.0
Shelby        1.0
Mercy         5.0
John          NaN
Name: hw1, dtype: float64

Name
Dorian       10.0
Jeannine      6.0
Iluminada     2.0
Luci          7.0
Jenny         8.0
Demetria      2.0
Michael       6.0
Garland       9.0
Shelby        1.0
Mercy         5.0
John          NaN
Name: hw1, dtype: float64

hw1   hw2
Name                 
Dorian     10.0  10.0
Jeannine    6.0   7.0
Iluminada   2.0   NaN
Luci        7.0   7.0
Jenny       8.0   NaN
Demetria    2.0   4.0
Michael     6.0  10.0
Garland     9.0   1.0
Shelby      1.0  10.0
Mercy       5.0   6.0
John        NaN  10.0

In [84]:
df.loc['Shelby', :]
df.loc[['Luci','Garland'],['hw1','Program']]

hw1           1
hw2          10
program    MSIS
Name: Shelby, dtype: object

C:\Users\60448\AppData\Local\Programs\Python\Python36\lib\site-packages\pandas\core\indexing.py:1418: FutureWarning:


Passing list-likes to .loc or [] with any missing label will raise
KeyError in the future, you can use .reindex() as an alternative.

See the documentation here:
https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#deprecate-loc-reindex-listlike



hw1  Program
Name                 
Luci     7.0      NaN
Garland  9.0      NaN

In [87]:
# 调取J开头的学生
df.index>='J'
df.index<='K'
(df.index>='J') & (df.index<='K')
df.loc[(df.index>='J') & (df.index<='K'),:]

array([False,  True, False,  True,  True, False,  True, False,  True,
        True,  True])

array([ True,  True,  True, False,  True,  True, False,  True, False,
       False,  True])

array([False,  True, False, False,  True, False, False, False, False,
       False,  True])

hw1   hw2 program
Name                       
Jeannine  6.0   7.0    MSIS
Jenny     8.0   NaN     NaN
John      NaN  10.0    MSIS

In [30]:
# 调取hw2所有最高分
df.hw2.max()
df.hw2 == df.hw2.max()
df.loc[df.hw2 == df.hw2.max(), :]
df.loc[df['hw2'] == df['hw2'].max(), ['hw1', 'program']]

# 或者用rank法
df[df.hw2.rank(ascending=False, method='min') == 1].loc[:, ['hw1', 'program']]

hw1 program
Name                 
Dorian   10.0    MSIS
Michael   6.0     MBA
Shelby    1.0    MSIS
John      NaN    MSIS

In [32]:
#  找到hw2大于5的hw1均分
df[df.hw2 > 5]['hw1'].mean()

5.833333333333333

##### sort用法

###### sort_values()

In [36]:
df.sort_values(by='hw1', ascending=False)
df.sort_values(by=['hw1','hw2'] ,ascending=[False,True])   # 并列时用hw2排序【排序有先后顺序】

hw1   hw2 program
Name                         
Dorian     10.0  10.0    MSIS
Garland     9.0   1.0    MSIS
Jenny       8.0   NaN     NaN
Luci        7.0   7.0    MSIS
Jeannine    6.0   7.0    MSIS
Michael     6.0  10.0     MBA
Mercy       5.0   6.0    MSIS
Demetria    2.0   4.0    MSIS
Iluminada   2.0   NaN     MBA
Shelby      1.0  10.0    MSIS
John        NaN  10.0    MSIS

###### sort_index()

In [37]:
df.sort_index()

hw1   hw2 program
Name                         
Demetria    2.0   4.0    MSIS
Dorian     10.0  10.0    MSIS
Garland     9.0   1.0    MSIS
Iluminada   2.0   NaN     MBA
Jeannine    6.0   7.0    MSIS
Jenny       8.0   NaN     NaN
John        NaN  10.0    MSIS
Luci        7.0   7.0    MSIS
Mercy       5.0   6.0    MSIS
Michael     6.0  10.0     MBA
Shelby      1.0  10.0    MSIS

In [60]:
# test1【用hw2成绩排序所有MSIS学生】
df[df.program=='MSIS'].sort_values(by='hw2')

#test2【显示hw2最高分学生的hw1成绩】
df[df.hw2 == df.hw2.max()]['hw1']

hw1   hw2 program
Name                        
Garland    9.0   1.0    MSIS
Demetria   2.0   4.0    MSIS
Mercy      5.0   6.0    MSIS
Jeannine   6.0   7.0    MSIS
Luci       7.0   7.0    MSIS
Dorian    10.0  10.0    MSIS
Shelby     1.0  10.0    MSIS
John       NaN  10.0    MSIS

Name
Dorian     10.0
Michael     6.0
Shelby      1.0
John        NaN
Name: hw1, dtype: float64

##### mean, min, max, etc

In [63]:
df.mean()  # 自动省略非数值型字段
df.mean(axis=1)  # axis默认是0=列，为1是在行方向应用mean

hw1    5.600000
hw2    7.222222
dtype: float64

Name
Dorian       10.0
Jeannine      6.5
Iluminada     2.0
Luci          7.0
Jenny         8.0
Demetria      3.0
Michael       8.0
Garland       5.0
Shelby        5.5
Mercy         5.5
John         10.0
dtype: float64

In [69]:
# test1 【计算两次hw差值的最大值的学生】
(df['hw1']-df['hw2']).abs()
(df['hw1']-df['hw2']).abs().nlargest(1)

Name
Dorian       0.0
Jeannine     1.0
Iluminada    NaN
Luci         0.0
Jenny        NaN
Demetria     2.0
Michael      4.0
Garland      8.0
Shelby       9.0
Mercy        1.0
John         NaN
dtype: float64

Name
Shelby    9.0
dtype: float64

##### Modifying DataFrames

In [70]:
df2 = df.copy()  #创建备份，互不影响

###### Add Rows

In [73]:
df2.loc['Oliver'] = [np.nan, 8, 'MSIS']
df2

hw1   hw2 program
Name                         
Dorian     10.0  10.0    MSIS
Jeannine    6.0   7.0    MSIS
Iluminada   2.0   NaN     MBA
Luci        7.0   7.0    MSIS
Jenny       8.0   NaN     NaN
Demetria    2.0   4.0    MSIS
Michael     6.0  10.0     MBA
Garland     9.0   1.0    MSIS
Shelby      1.0  10.0    MSIS
Mercy       5.0   6.0    MSIS
John        NaN  10.0    MSIS
Oliver      NaN   8.0    MSIS

###### Add columns

In [76]:
df2 = df.copy()

In [ ]:
df2['hw3'] = 0

In [77]:
## add calculated columns
df2['final'] = 0.2 * df2.hw1 + 0.8 * df.hw2
df2

hw1   hw2 program  final
Name                                
Dorian     10.0  10.0    MSIS   10.0
Jeannine    6.0   7.0    MSIS    6.8
Iluminada   2.0   NaN     MBA    NaN
Luci        7.0   7.0    MSIS    7.0
Jenny       8.0   NaN     NaN    NaN
Demetria    2.0   4.0    MSIS    3.6
Michael     6.0  10.0     MBA    9.2
Garland     9.0   1.0    MSIS    2.6
Shelby      1.0  10.0    MSIS    8.2
Mercy       5.0   6.0    MSIS    5.8
John        NaN  10.0    MSIS    NaN